### ISSUE TITLE
Keyboard Freezes when external sources of electricity be it EM or ESD affect it's normal operation

### ISSUE THREAD

**Issue by AlexDygma** [Dygmalab/Raise-Firmware#12]
We have been exploring for quite some time the reasons behind the freezes the users where experiencing, with this update we plan to restart, mitigate and after reduce to a minimum this phenomenon.

the circumstances on which this happens are the following:

- ESD released upon the keyboard due to human interaction
- EM affecting the keyboard due to home appliances affecting it (like freezers or heaters)
- Connection or disconnection of cables can also trigger bus interruption

All of this electrical phenomenon's affect the i2c bus in a bad way up to the point to freeze the whole chip altogether.

Arduino has a i2c library which is known to be really bad at handling i2c freezes so it needs to be improved or swapped.

**Comment by AlexDygma** [comment]
Added first step of the freeze fix by configuring a watchdog to turn the freezes to restarts

**Comment by HomerSp** [comment]
So I managed to reproduce this by using an electrical lighter and can confirm the watchdog is doing its job! The board seems to be very sensitive because I tried taking the PCB out and added some plastic washers between the case and the PCB but it still happened. So I then placed the PCB on top of the palm pads and used the electric lighter on the case, but it still caused the reboot - so I don't really know what's going on there.

When searching around I found this: https://github.com/arduino/ArduinoCore-samd/pull/535 and while that does help to alleviate it somewhat, it still locks up or reboots (with the watchdog) just not as often.

**Comment by AlexDygma** [comment]
Hey @HomerSp! 

I forked a fix for the freezes that applies the latest SERCOM update from Arduino to solve communication problems with i2c:
https://github.com/Dygmalab/Kaleidoscope-Bundle-Dygma/tree/freezeFix

With that fork i managed to prevent the blocking altogether, so the neuron no longer restarts, but it freezes because the sides cannot maintain connection when something happens to them.

im going to review the side FW now to see if i can patch the way it works, or if not, we should be able to restart the i2c channel from the master.

Ill be experimenting with this fixes the next days, so ill update here any progress i manage to do to get you informed and to leave trace 😄 

See u!

**Comment by AlexDygma** [comment]
When using a logic analyzer to fetch information about the problem that made the i2c bus stall, i found the following:
- The SLC line remains at 5V
- The SDA line remains at 0V

**Comment by AlexDygma** [comment]
Issue closed with the #13 merge
