### ISSUE TITLE
Master build does not support Layers or Macros

### ISSUE THREAD

**Issue by landrito** [Dygmalab/Raise-Firmware#7]
Running `make build` and passing the `ino.hex` to Bazecor causes macros to not work and layershifting to not work on Layers greater than 0.

**Comment by AlexDygma** [comment]
Hello landrito!

Yes, the modifcations that enable the macros to work are not in our repository, they are in the kaleidoscope library, not our repo, i'm trying to fix this issue for everyone by adding the files to our own repo so that we can compile without modifying the behaviour of the rest of the firmware, but it's taking me some time.

**Comment by landrito** [comment]
Great thanks for the update! Another question, will those mouse speed variables ever be exposed in the Bazecor UI?

**Comment by AlexDygma** [comment]
> Great thanks for the update! Another question, will those mouse speed variables ever be editable in the Bazecor UI?

That's the plan :)

We will make that available in the next update, with more configurations added for even more parameters of the raise, to avoid debouncing with specific kinds of keycaps and more.

so stay tuned!

**Comment by AlexDygma** [comment]
Hello Everyone,

The new documentation / Fork of keyboardio in which to store the recent changes to the firmware is ready, this means you can from now on download the repo, use the new tools and always have the latest version of the Firmware available.

be sure to re download the libraries as they have undergone changes.

follow the instructions to keep the repo updated.
